/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar;

import java.sql.*;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

/**
 *
 * @author naufa
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        initAllList();
    }
    
    public void initAllList() {
        
        try {
            ResultSet rs;
            DBConn db = new DBConn();


            rs = db.queryAllAsesmenFromDB(user);
            if (rs != null) {
                while (rs.next()) {

                    if (rs.getString("jenisAsesmen").equals("jantung")) {
                        user.getRiwayatAsesmen().add(new AsesmenJantung(rs.getString("jenisAsesmen"), rs.getString("tanggal"), rs.getInt("usia"),rs.getInt("sis"),rs.getInt("dia"), 
                            rs.getFloat("tinggi"), rs.getFloat("berat")));
                    } else if (rs.getString("jenisAsesmen").equals("diabetes")) {
                        user.getRiwayatAsesmen().add(new AsesmenDiabetes(rs.getString("jenisAsesmen"), rs.getString("tanggal"), rs.getInt("usia"),rs.getInt("sis"),rs.getInt("dia"), 
                            rs.getFloat("tinggi"), rs.getFloat("berat")));
                    } else {
                        user.getRiwayatAsesmen().add(new AsesmenStroke(rs.getString("jenisAsesmen"), rs.getString("tanggal"), rs.getInt("usia"),rs.getInt("sis"),rs.getInt("dia"), 
                            rs.getFloat("tinggi"), rs.getFloat("berat")));
                    }

                }
            }
            
            this.listRiwayatAsesmen.setListData(this.user.getAsesmenHighlight());


//            rs = db.queryAllKonsultasiFromDB(user);
//            if (rs != null) {
//                while (rs.next()) {
//
//                    user.getRiwayatKonsultasi().add(new Konsultasi(rs.getString("pesan"), rs.getString("balasan"), rs.getString("tanggal")));
//
//                }
//            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupKonsultasi = new javax.swing.ButtonGroup();
        jLabel18 = new javax.swing.JLabel();
        buttonGroupNyeriDada = new javax.swing.ButtonGroup();
        buttonGroupJantungBerdebar = new javax.swing.ButtonGroup();
        buttonGroupKeturunanDiabetes = new javax.swing.ButtonGroup();
        buttonGroupMatiRasa = new javax.swing.ButtonGroup();
        buttonGroupJenisAsesmen = new javax.swing.ButtonGroup();
        jColorChooser1 = new javax.swing.JColorChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        inputUmur = new javax.swing.JTextField();
        inputTinggi = new javax.swing.JTextField();
        inputBerat = new javax.swing.JTextField();
        inputTekananSistolik = new javax.swing.JTextField();
        inputTekananDiatolik = new javax.swing.JTextField();
        radioYaNyeriDada = new javax.swing.JRadioButton();
        radioTidakNyeriDada = new javax.swing.JRadioButton();
        radioYaJantungBerdebar = new javax.swing.JRadioButton();
        radioYaDiabetes = new javax.swing.JRadioButton();
        radioYaMatiRasa = new javax.swing.JRadioButton();
        radioTidakJantungBerdebar = new javax.swing.JRadioButton();
        radioTidakDiabetes = new javax.swing.JRadioButton();
        radioTidakMatiRasa = new javax.swing.JRadioButton();
        buttonSubmitAsesmen = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        radioJenisJantung = new javax.swing.JRadioButton();
        radioJenisDiabetes = new javax.swing.JRadioButton();
        radioJenisStroke = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listRiwayatAsesmen = new javax.swing.JList<>();
        rincianTekananDarah = new javax.swing.JLabel();
        rincianTinggiBadan = new javax.swing.JLabel();
        rincianBeratBadan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rincianUsia = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pesanJantungRadio = new javax.swing.JRadioButton();
        pesanDiabetesRadio = new javax.swing.JRadioButton();
        pesanStrokeRadio = new javax.swing.JRadioButton();
        kirimPesanButton = new javax.swing.JButton();
        balasanDisplay = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRiwayatKonsultasi = new javax.swing.JList<>();

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Riwayat Asesmen");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Umur");

        jLabel10.setText("Tinggi Badan");

        jLabel11.setText("Berat Badan");

        jLabel12.setText("Tekanan Darah Sistolik");

        jLabel13.setText("Tekanan Darah Diatolik");

        jLabel14.setText("Apakah Anda sering nyeri dada?");

        jLabel15.setText("Apakah jantung Anda sering berdebar?");

        jLabel16.setText("Apakah Anda memiliki keturunan diabetes?");

        jLabel17.setText("Apakah Anda sering merasakan mati rasa?");

        inputUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUmurActionPerformed(evt);
            }
        });

        inputTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTinggiActionPerformed(evt);
            }
        });

        inputBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBeratActionPerformed(evt);
            }
        });

        buttonGroupNyeriDada.add(radioYaNyeriDada);
        radioYaNyeriDada.setText("Ya");
        radioYaNyeriDada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioYaNyeriDadaActionPerformed(evt);
            }
        });

        buttonGroupNyeriDada.add(radioTidakNyeriDada);
        radioTidakNyeriDada.setText("Tidak");

        buttonGroupJantungBerdebar.add(radioYaJantungBerdebar);
        radioYaJantungBerdebar.setText("Ya");
        radioYaJantungBerdebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioYaJantungBerdebarActionPerformed(evt);
            }
        });

        buttonGroupKeturunanDiabetes.add(radioYaDiabetes);
        radioYaDiabetes.setText("Ya");
        radioYaDiabetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioYaDiabetesActionPerformed(evt);
            }
        });

        buttonGroupMatiRasa.add(radioYaMatiRasa);
        radioYaMatiRasa.setText("Ya");
        radioYaMatiRasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioYaMatiRasaActionPerformed(evt);
            }
        });

        buttonGroupJantungBerdebar.add(radioTidakJantungBerdebar);
        radioTidakJantungBerdebar.setText("Tidak");
        radioTidakJantungBerdebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTidakJantungBerdebarActionPerformed(evt);
            }
        });

        buttonGroupKeturunanDiabetes.add(radioTidakDiabetes);
        radioTidakDiabetes.setText("Tidak");
        radioTidakDiabetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTidakDiabetesActionPerformed(evt);
            }
        });

        buttonGroupMatiRasa.add(radioTidakMatiRasa);
        radioTidakMatiRasa.setText("Tidak");
        radioTidakMatiRasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTidakMatiRasaActionPerformed(evt);
            }
        });

        buttonSubmitAsesmen.setText("Submit");
        buttonSubmitAsesmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitAsesmenActionPerformed(evt);
            }
        });

        jLabel20.setText("Jenis Asesmen");

        buttonGroupJenisAsesmen.add(radioJenisJantung);
        radioJenisJantung.setText("Jantung");
        radioJenisJantung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioJenisJantungActionPerformed(evt);
            }
        });

        buttonGroupJenisAsesmen.add(radioJenisDiabetes);
        radioJenisDiabetes.setText("Diabetes");

        buttonGroupJenisAsesmen.add(radioJenisStroke);
        radioJenisStroke.setText("Stroke");
        radioJenisStroke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioJenisStrokeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioYaMatiRasa)
                                .addGap(18, 18, 18)
                                .addComponent(radioTidakMatiRasa))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioYaDiabetes)
                                .addGap(18, 18, 18)
                                .addComponent(radioTidakDiabetes))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(radioYaNyeriDada)
                                            .addComponent(radioYaJantungBerdebar))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioTidakJantungBerdebar)
                                            .addComponent(radioTidakNyeriDada)))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(inputTekananSistolik, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputTekananDiatolik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(inputUmur, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputTinggi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(radioJenisJantung)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioJenisDiabetes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioJenisStroke))))
                            .addComponent(jLabel20)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(buttonSubmitAsesmen)))
                .addGap(0, 376, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioJenisDiabetes)
                            .addComponent(radioJenisJantung)
                            .addComponent(radioJenisStroke)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(inputUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(inputTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inputBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(inputTekananSistolik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(inputTekananDiatolik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(radioYaNyeriDada)
                    .addComponent(radioTidakNyeriDada))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(radioYaJantungBerdebar)
                    .addComponent(radioTidakJantungBerdebar))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(radioYaDiabetes)
                    .addComponent(radioTidakDiabetes))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(radioYaMatiRasa)
                    .addComponent(radioTidakMatiRasa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSubmitAsesmen)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asesmen", jPanel4);

        listRiwayatAsesmen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listRiwayatAsesmenMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(listRiwayatAsesmen);

        rincianTekananDarah.setText("Tekanan Darah");

        rincianTinggiBadan.setText("Tinggi Badan");

        rincianBeratBadan.setText("Berat Badan");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Riwayat Asesmen");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Rincian Asesmen");

        rincianUsia.setText("Umur");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rincianTekananDarah)
                    .addComponent(rincianTinggiBadan)
                    .addComponent(rincianBeratBadan)
                    .addComponent(rincianUsia))
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(89, 89, 89))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(rincianTekananDarah)
                        .addGap(31, 31, 31)
                        .addComponent(rincianTinggiBadan)
                        .addGap(29, 29, 29)
                        .addComponent(rincianBeratBadan)
                        .addGap(29, 29, 29)
                        .addComponent(rincianUsia))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Riwayat Asesmen", jPanel5);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Balasan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Pesan Cepat");

        buttonGroupKonsultasi.add(pesanJantungRadio);
        pesanJantungRadio.setText("Saya Positif Jantung");
        pesanJantungRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanJantungRadioActionPerformed(evt);
            }
        });

        buttonGroupKonsultasi.add(pesanDiabetesRadio);
        pesanDiabetesRadio.setText("Saya Positif Diabetes");

        buttonGroupKonsultasi.add(pesanStrokeRadio);
        pesanStrokeRadio.setText("Saya Positif Stroke");

        kirimPesanButton.setText("Kirim");
        kirimPesanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimPesanButtonActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Riwayat Konsultasi");

        jScrollPane1.setViewportView(listRiwayatKonsultasi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pesanJantungRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesanDiabetesRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesanStrokeRadio))
                            .addComponent(balasanDisplay)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(kirimPesanButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel19)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pesanJantungRadio)
                    .addComponent(pesanDiabetesRadio)
                    .addComponent(pesanStrokeRadio))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(balasanDisplay))
                .addGap(18, 18, 18)
                .addComponent(kirimPesanButton)
                .addGap(30, 30, 30)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Konsultasi", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUmurActionPerformed

    private void radioYaNyeriDadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioYaNyeriDadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioYaNyeriDadaActionPerformed

    private void radioYaJantungBerdebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioYaJantungBerdebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioYaJantungBerdebarActionPerformed

    private void radioYaDiabetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioYaDiabetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioYaDiabetesActionPerformed

    private void radioYaMatiRasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioYaMatiRasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioYaMatiRasaActionPerformed

    private void radioTidakJantungBerdebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTidakJantungBerdebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTidakJantungBerdebarActionPerformed

    private void radioTidakDiabetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTidakDiabetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTidakDiabetesActionPerformed

    private void radioTidakMatiRasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTidakMatiRasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTidakMatiRasaActionPerformed

    private void inputBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBeratActionPerformed

    private void inputTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTinggiActionPerformed

    private void buttonSubmitAsesmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitAsesmenActionPerformed
        // TODO add your handling code here:
        
        String jenisAsesmen;
        int umur, sis, dia;
        float tinggi, berat;
        if (this.radioJenisJantung.isSelected()){
            jenisAsesmen = "jantung";
        } else if (this.radioJenisDiabetes.isSelected()){
            jenisAsesmen = "diabetes";
        } else {
            jenisAsesmen = "stroke";
        }
        
        umur = Integer.valueOf(this.inputUmur.getText());
        sis = Integer.valueOf(this.inputTekananSistolik.getText());
        dia = Integer.valueOf(this.inputTekananDiatolik.getText());
        
        
        tinggi = Float.valueOf(this.inputTinggi.getText());
        berat = Float.valueOf(this.inputBerat.getText());
        
        boolean nyeriDada, jantungBerdebar, keturunanDiabetes, matiRasa;
        if (this.radioYaJantungBerdebar.isSelected()) {
            jantungBerdebar = true;
        } else {
            jantungBerdebar = false;
        }
        if (this.radioYaNyeriDada.isSelected()) {
            nyeriDada = true;
        } else {
            nyeriDada = false;
        }
        if (this.radioYaDiabetes.isSelected()) {
            keturunanDiabetes = true;
        } else {
            keturunanDiabetes = false;
        }
        if (this.radioYaMatiRasa.isSelected()) {
            matiRasa = true;
        } else {
            matiRasa = false;
        }
        
        
        
        Asesmen a = this.user.asesmen(jenisAsesmen, this.user, umur, sis, dia, tinggi, berat, nyeriDada, jantungBerdebar, keturunanDiabetes, matiRasa);
        
        
        
        this.listRiwayatAsesmen.setListData(user.getAsesmenHighlight());
        
        JOptionPane.showMessageDialog(this, "Hasil diagnosis asesmen " + jenisAsesmen + ": " + a.getHasilDiagnosis());
        
        this.inputBerat.setText("");
        this.inputTekananDiatolik.setText("");
        this.inputTekananSistolik.setText("");
        this.inputTinggi.setText("");
        this.inputUmur.setText("");
        
        this.buttonGroupJantungBerdebar.clearSelection();
        this.buttonGroupJenisAsesmen.clearSelection();
        
        
        this.buttonGroupKeturunanDiabetes.clearSelection();
        this.buttonGroupMatiRasa.clearSelection();
        this.buttonGroupNyeriDada.clearSelection();
        
        DBConn db = new DBConn();
        db.insertAsesmenToDB(a);
        
       
    }//GEN-LAST:event_buttonSubmitAsesmenActionPerformed

    private void pesanJantungRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanJantungRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesanJantungRadioActionPerformed

    private void kirimPesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimPesanButtonActionPerformed
        // TODO add your handling code here:
        String jenisPesan;
        if (this.pesanDiabetesRadio.isSelected()){
            jenisPesan = "diabetes";
        } else if (this.pesanJantungRadio.isSelected()){
            jenisPesan = "jantung";
        } else {
            jenisPesan = "stroke";
        }
        
        String balasan = user.konsultasi(jenisPesan).getBalasan();
        this.balasanDisplay.setText(balasan);
        
        
        
        this.listRiwayatKonsultasi.setListData(user.getKonsultasiHighlight());
        
        this.buttonGroupKonsultasi.clearSelection();
        
//        DBConn db = new DBConn();
//        db.insertKonsultasiToDB(k);
    }//GEN-LAST:event_kirimPesanButtonActionPerformed

    private void radioJenisJantungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioJenisJantungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioJenisJantungActionPerformed

    private void radioJenisStrokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioJenisStrokeActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_radioJenisStrokeActionPerformed

    private void listRiwayatAsesmenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listRiwayatAsesmenMousePressed
        // TODO add your handling code here:
        
        int selectedAsesmenIndex = this.listRiwayatAsesmen.getSelectedIndex();
        
        Asesmen a = this.user.getRiwayatAsesmen().get(selectedAsesmenIndex);
        
        this.rincianBeratBadan.setText("Berat Badan: " + a.getBeratBadan());
        this.rincianTinggiBadan.setText("Tinggi Badan: " + a.getTinggiBadan());
        this.rincianUsia.setText("Umur: " + a.getUsia());
        this.rincianTekananDarah.setText("Tekanan Darah: " + a.getTekananDarahSis() + "/" + a.getTekananDarahDia());
    }//GEN-LAST:event_listRiwayatAsesmenMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balasanDisplay;
    private javax.swing.ButtonGroup buttonGroupJantungBerdebar;
    private javax.swing.ButtonGroup buttonGroupJenisAsesmen;
    private javax.swing.ButtonGroup buttonGroupKeturunanDiabetes;
    private javax.swing.ButtonGroup buttonGroupKonsultasi;
    private javax.swing.ButtonGroup buttonGroupMatiRasa;
    private javax.swing.ButtonGroup buttonGroupNyeriDada;
    private javax.swing.JButton buttonSubmitAsesmen;
    private javax.swing.JTextField inputBerat;
    private javax.swing.JTextField inputTekananDiatolik;
    private javax.swing.JTextField inputTekananSistolik;
    private javax.swing.JTextField inputTinggi;
    private javax.swing.JTextField inputUmur;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kirimPesanButton;
    private javax.swing.JList<String> listRiwayatAsesmen;
    private javax.swing.JList<String> listRiwayatKonsultasi;
    private javax.swing.JRadioButton pesanDiabetesRadio;
    private javax.swing.JRadioButton pesanJantungRadio;
    private javax.swing.JRadioButton pesanStrokeRadio;
    private javax.swing.JRadioButton radioJenisDiabetes;
    private javax.swing.JRadioButton radioJenisJantung;
    private javax.swing.JRadioButton radioJenisStroke;
    private javax.swing.JRadioButton radioTidakDiabetes;
    private javax.swing.JRadioButton radioTidakJantungBerdebar;
    private javax.swing.JRadioButton radioTidakMatiRasa;
    private javax.swing.JRadioButton radioTidakNyeriDada;
    private javax.swing.JRadioButton radioYaDiabetes;
    private javax.swing.JRadioButton radioYaJantungBerdebar;
    private javax.swing.JRadioButton radioYaMatiRasa;
    private javax.swing.JRadioButton radioYaNyeriDada;
    private javax.swing.JLabel rincianBeratBadan;
    private javax.swing.JLabel rincianTekananDarah;
    private javax.swing.JLabel rincianTinggiBadan;
    private javax.swing.JLabel rincianUsia;
    // End of variables declaration//GEN-END:variables

    private User user;
    
    

    public JLabel getBalasanDisplay() {
        return balasanDisplay;
    }

    public void setBalasanDisplay(JLabel balasanDisplay) {
        this.balasanDisplay = balasanDisplay;
    }

    

    public JList<String> getListRiwayatAsesmen() {
        return listRiwayatAsesmen;
    }

    public void setListRiwayatAsesmen(JList<String> listRiwayatAsesmen) {
        this.listRiwayatAsesmen = listRiwayatAsesmen;
    }

    public JRadioButton getPesanDiabetesRadio() {
        return pesanDiabetesRadio;
    }

    public void setPesanDiabetesRadio(JRadioButton pesanDiabetesRadio) {
        this.pesanDiabetesRadio = pesanDiabetesRadio;
    }

    public JRadioButton getPesanJantungRadio() {
        return pesanJantungRadio;
    }

    public void setPesanJantungRadio(JRadioButton pesanJantungRadio) {
        this.pesanJantungRadio = pesanJantungRadio;
    }

    public JRadioButton getPesanStrokeRadio() {
        return pesanStrokeRadio;
    }

    public void setPesanStrokeRadio(JRadioButton pesanStrokeRadio) {
        this.pesanStrokeRadio = pesanStrokeRadio;
    }

    public JLabel getRincianBeratBadan() {
        return rincianBeratBadan;
    }

    public void setRincianBeratBadan(JLabel rincianBeratBadan) {
        this.rincianBeratBadan = rincianBeratBadan;
    }

    public JLabel getRincianTekananDarah() {
        return rincianTekananDarah;
    }

    public void setRincianTekananDarah(JLabel rincianTekananDarah) {
        this.rincianTekananDarah = rincianTekananDarah;
    }

    public JLabel getRincianTinggiBadan() {
        return rincianTinggiBadan;
    }

    public void setRincianTinggiBadan(JLabel rincianTinggiBadan) {
        this.rincianTinggiBadan = rincianTinggiBadan;
    }

    public JButton getSubmitAsesmenButton() {
        return buttonSubmitAsesmen;
    }

    public void setSubmitAsesmenButton(JButton submitAsesmenButton) {
        this.buttonSubmitAsesmen = submitAsesmenButton;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    
    
}
